name: inventario-devops

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - itens-service
    restart: unless-stopped
    networks:
      - inventario-net

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: ghcr.io/gil2004/inventario-auth:${TAG:-latest}
    deploy:
      replicas: 2
    restart: unless-stopped
    networks:
      - inventario-net
    environment:
      OTEL_SERVICE_NAME: auth-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318

  itens-service:
    build:
      context: .
      dockerfile: itens-service/Dockerfile
    image: ghcr.io/gil2004/inventario-itens:${TAG:-latest}
    environment:
      AUTH_URL: http://auth-service:5001
      DB_PATH: /data/itens.db
      OTEL_SERVICE_NAME: itens-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    volumes:
      - itens-data:/data
    deploy:
      replicas: 2
    restart: unless-stopped
    depends_on:
      - auth-service
    networks:
      - inventario-net

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"
    restart: unless-stopped  
    networks:
      - inventario-net

networks:
  inventario-net:
    ipam:
      config:
        - subnet: 172.28.0.0/24

volumes:
  itens-data:

  